export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const SET_POPULAR_TVSHOWS = "SET_POPULAR_TVSHOWS";
export const SET_TVSHOW_GENRES = "SET_TVSHOW_GENRES";